Args warning
T8T9/paddle1to2 pull request #5
Opened 2020-08-29 09:48 UTC by MingMingShangTian

refactor_kwargs implement

2020-08-30 04:33 UTC, T8T9 requested changes

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +    def _get_number_from_arglist(index, arg_list):
提取value用处不大，用参数名定位，
另外提取value的逻辑有问题，value还可能是 object 或string之类的

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +    def _refector_args(node, capture, fn):
用 `def _norm(node: LN, capture: Capture, filename: Filename) -> None:` 这种格式

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +        fp = capture["function_parameters"]
fp换个有意义的名字，api_node 之类的，name也是

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +        if "args_change" in change_spec[func_name]:
用 `args_change = change_spec.get('func_name', [])`, 可以省去一层缩进

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                if len(arg_tuple) == 3:
增删改查参数，需要打印info日志

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                    arg_node = KeywordArg(Name(new_arg), Number(arg_val))
用户指定的不一定都是Number

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                    node_list.append(arg_node)
每一步操作都需要直接修改原ast，否则下一步修改可能看不到上一步的修改，如新增的参数，如果重命名或删除的时候就找不到了

另外修改节点，需要加上原来的prefix

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                        logger.Warning("can not rename or delete argument because raw argument is empty")
raw argument -> argument list

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                    if fp.children == [LParen(), RParen()]:
不需要创建两个新对象，直接用TOKEN.LPAR, TOKEN.RPAR判断即可

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                    elif fp.children[1].type == TOKEN.NUMBER:
不是只有NUMBER

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                        #del
删除一个节点直接用node.remove()

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                        #rename
rename 直接修改 value

2020-08-30 04:33 UTC, T8T9 commented on paddle1to2/refactor.py
> +                    else:
给每个if else 加上注释，举个例子

2020-08-30 04:36 UTC, T8T9 requested changes

2020-08-30 04:36 UTC, T8T9 commented on paddle1to2/transformers.py
> +        fp.children[1].children.append(Comma())
用insert_child

2020-08-31 02:32 UTC, T8T9 requested changes

2020-08-31 02:32 UTC, T8T9 commented on paddle1to2/tests/test_refactor.py
> +
删除多余空行，两个即可

2020-08-31 02:32 UTC, T8T9 commented on paddle1to2/tests/test_refactor.py
> +        paddle.add(1,y=2)
加上两个case，
- `paddle.add(1)`
- `paddle.add(a=3, b=4, c=5)`

2020-08-31 02:32 UTC, T8T9 commented on paddle1to2/tests/test_refactor.py
> +                [
每个变换写到一行吧，spec.py 中的是json.dumps 出来的，所以有换行，咱们写的话最好还是写到一行

2020-08-31 02:32 UTC, T8T9 commented on paddle1to2/tests/test_refactor.py
> +        paddle.add(x=1,out=2)
1. 没有测试rename的情况
2. 增加case:
- `paddle.add()`
- `paddle.add(1, x=2)`

2020-08-31 02:32 UTC, T8T9 commented on paddle1to2/tests/test_refactor.py
> +                    "x"
这是rename？名称应该不同吧

2020-08-31 02:35 UTC, MingMingShangTian commented on paddle1to2/tests/test_refactor.py
> +                    "x"
这个是PM给的例子中有的

2020-08-31 03:26 UTC, T8T9 requested changes

2020-08-31 03:26 UTC, T8T9 commented on paddle1to2/refactor.py
> +            if len(arg_tuple) == 3:
要判断第一个元素是空串

2020-08-31 03:26 UTC, T8T9 commented on paddle1to2/refactor.py
> +                    func_para_node.insert_child(1,arg_node )
空格位置错了

2020-08-31 04:10 UTC, T8T9 approved these changes

2020-08-31 04:10 UTC, merged